### ISSUE TITLE
Use latest version of `mpesa` crate

### ISSUE THREAD

**Issue by c12i** [dennohpeter/autop2p#1]
Hi @dennohpeter. The current version of `mpesa` you are using, `0.4.2`, is very outdated.

I recommend using a `git` version as I am preparing to release `v1-beta` very soon to crates.io:

```toml
[dependencies]
mpesa = { git = "https://github.com/collinsmuriuki/mpesa-rust" }
```

You can also install based on features you are using by choosing from the list below: 
`b2b`
`b2c`
`account_balance`
`c2b_register`
`c2b_simulate`
`express_request`
`transaction_reversal`

```toml
[dependencies]
mpesa = { git = "https://github.com/collinsmuriuki/mpesa-rust", default_features = false, features = ["b2b", "express_request"] }
```
